Output docs/images/workspace.gif
Source docs/demos/common.tape
Source docs/demos/start.tape
Type "# Save cloud + Kubernetes + Docker, with ADC enabled"
Enter
Sleep 3s
Type "chop"
Enter
Sleep 1s
Type "I"
Sleep 1s
Space
Sleep 1s
Type "P"
Sleep 1s
Space
Type "K"
Sleep 1s
Down
Space
Sleep 2s
Type "D"
Sleep 1s
Space
Sleep 1s
Type "A"
Sleep 2s
Ctrl+W
Sleep 1s
Type "Services Dev"
Enter
Sleep 3s
Enter
Sleep 2s
Enter
Sleep 2s
Type "c"
Type "W"
Type "/services"
Sleep 1s
Escape
Sleep 500ms
Space
Sleep 4s
Hide
Ctrl+C
Type "exit"
Enter
